export interface Project {
  slug: string;
  title: string;
  tagline: string;
  proofLine: string;
  role: string;
  stack: string[];
  links: {
    caseStudy?: string;
    demo?: string;
    video?: string;
    repo?: string;
  };
  category: "featured" | "ai" | "fullstack" | "experiment";
}

export const projects: Project[] = [
  {
    slug: "injured",
    title: "INJURED Mobile App",
    tagline: "Athlete injury tracking and recovery management",
    proofLine:
      "HIPAA-grade encryption, real-time sync, AI-powered recovery guidance.",
    role: "Lead Engineer • Full stack + AI + Security",
    stack: [
      "Expo",
      "React Native",
      "Convex",
      "Clerk",
      "AWS KMS",
    ],
    links: { caseStudy: "/projects/injured" },
    category: "featured",
  },
  {
    slug: "orthohcp",
    title: "OrthoHCP Mobile App",
    tagline: "AI video interviewer for healthcare provider onboarding",
    proofLine:
      "Shipped a full product in 30 days: video workflow + AI interview logic.",
    role: "Lead dev • Full stack + AI",
    stack: [
      "Flutter",
      "TypeScript",
      "OpenAI",
      "Supabase",
    ],
    links: { caseStudy: "/projects/orthohcp", demo: "https://play.google.com/store/apps/details?id=com.orthohcp.app" },
    category: "featured",
  },
  {
    slug: "shakespeare-ml",
    title: "Shakespeare ML",
    tagline: "AI model written and trained from scratch",
    proofLine: "Educational ML model showing training process step-by-step.",
    role: "Solo dev",
    stack: ["Python", "PyTorch", "Astro", "SolidJS"],
    links: { demo: "https://ml.useswiftcode.com" },
    category: "featured",
  },
  {
    slug: "gameface",
    title: "GameFace",
    tagline: "AI automation for sales grading",
    proofLine: "Contract work:Automated sales training via fine-tuned AI.",
    role: "ML Engineer",
    stack: ["Next.js", "OpenAI", "Convex"],
    links: { demo: "https://gameface.useswiftcode.com" },
    category: "ai",
  },
  {
    slug: "askdb",
    title: "AskDB",
    tagline: "Talk to your database via AI",
    proofLine: "Natural language → safe SQL + answers with guardrails.",
    role: "Solo dev • Side project",
    stack: ["Next.js", "TypeScript", "OpenAI", "OpenSource"],
    links: { demo: "https://askdb.useswiftcode.com" },
    category: "experiment",
  },
  {
    slug: "injured-connect",
    title: "INJURED CONNECT",
    tagline: "Patient management portal for health care providers (in development)",
    proofLine: "Connected web experience health care providers.",
    role: "Lead developer",
    stack: ["React Router", "TypeScript", "OpenAI", "Convex", "TurboRepo"],
    links: {},
    category: "fullstack",
  },
  {
    slug: "orthodata",
    title: "OrthoData",
    tagline: "PT patient management and testing platform",
    proofLine: "PT patient management and testing platform.",
    role: "Full stack developer",
    stack: ["React", "Supabase"],
    links: { demo: "https://data.ortho-patient.com" },
    category: "featured",
  },
  {
    slug: "orthoathlete",
    title: "OrthoAthlete",
    tagline: "Athlete-facing recovery experience",
    proofLine: "Companion app for intake, guidance, and progress tracking.",
    role: "Full stack developer",
    stack: ["Flutter", "Express.js", "MySQL", "AWS"],
    links: { demo: "https://play.google.com/store/apps/details?id=com.app.orthopatient"},
    category: "fullstack",
  },
  {
    slug: "orthopatient",
    title: "OrthoPatient",
    tagline: "Patient-facing recovery experience",
    proofLine: "Companion app for intake, guidance, and progress tracking.",
    role: "Full stack developer",
    stack: ["Flutter", "Express.js", "MySQL", "AWS"],
    links: { demo: "https://play.google.com/store/apps/details?id=com.orthopatient.app"},
    category: "fullstack",
  },
  {
    slug: "orthoagent",
    title: "OrthoAgent",
    tagline: "AI testing for INJURED's AI model",
    proofLine: "Test MRI Analysis, edit system prompts, and more.",
    role: "AI Engineer",
    stack: ["Next.js", "OpenAI", "Convex", "TurboRepo"],
    links: { demo: "https://agent.ortho-patient.com" },
    category: "ai",
  },
  {
    slug: "loan-origination",
    title: "Loan Orignator Service",
    tagline: "Exploring Kotlin, Kafka, and Spring Boot",
    proofLine: "Tested out microservice architecture with Kotlin, Kafka, and Spring Boot",
    role: "Developer",
    stack: ["Kotlin/Java", "Kafka", "Spring Boot", "Microservices"],
    links: { demo: "https://github.com/canyonbryson/loan-origination" },
    category: "experiment",
  },
  {
    slug: "road-rally",
    title: "Road Rally",
    tagline: "Interactive scavenger hunt app",
    proofLine: "Full stack app with real-time multiplayer features.",
    role: "Lead developer",
    stack: ["Astro", "SolidJS", "React Native", "AWS", "DynamoDB", "Planetscale + Drizzle ORM"],
    links: { demo: "https://www.riddlerroadrally.com" },
    category: "fullstack",
  },
  {
    slug: "boat",
    title: "Boat",
    tagline: "Event-driven task manager",
    proofLine: "Workflow system built around events and automations.",
    role: "Developer",
    stack: ["Event-driven", "Workflow", "Web app", "SolidJS"],
    links: {},
    category: "fullstack",
  },
  {
    slug: "worm",
    title: "Worm",
    tagline: "Image recognition and automation project",
    proofLine: "Custom image recognition for real-world classification tasks.",
    role: "Developer",
    stack: ["Computer vision", "ML", "Electron", "Javascript", "Automation"],
    links: {},
    category: "ai",
  },
  {
    slug: "pocketmonsters",
    title: "Pocket Monsters",
    tagline: "Nuxt + Vue exploration project",
    proofLine: "Tested out Nuxt + Vue",
    role: "Developer",
    stack: ["Nuxt", "Vue", "Web app", "SPA"],
    links: { demo: "https://pocketmonsters.vercel.app" },
    category: "experiment",
  },
  {
    slug: "rec-center",
    title: "Rec Center",
    tagline: "Season scheduling platform",
    proofLine: "Scheduling tools for sports programs and facilities.",
    role: "Developer",
    stack: ["Scheduling", "Web app", "SPA", "Astro + SolidJS"],
    links: {},
    category: "fullstack",
  },
  {
    slug: "food-storage",
    title: "Food Storage",
    tagline: "Planning and tracking system",
    proofLine: "Inventory and planning tools for long-term storage.",
    role: "Developer",
    stack: ["SPA", "Astro + SolidJS", "Prisma"],
    links: {},
    category: "fullstack",
  },
  {
    slug: "useswiftcode",
    title: "UseSwiftCode AI",
    tagline: "AI personal assistant builder (Deprecated)",
    proofLine: "Platform for building custom AI chatbots and automations.",
    role: "Solo dev",
    stack: ["Astro", "SolidJS", "SST", "DynamoDB", "TypeScript"],
    links: { demo: "https://www.useswiftcode.com" },
    category: "ai",
  },
  {
    slug: "mood-tracker",
    title: "MOOd Tracker",
    tagline: "Cow-themed mood and habit tracker for my wife",
    proofLine: "Flutter app that analyzes habits to identify causes of mood changes.",
    role: "Developer",
    stack: ["Flutter", "TypeScript"],
    links: { },
    category: "experiment",
  },
  {
    slug: "dex-swap",
    title: "DEX Swap",
    tagline: "Crypto exchange website",
    proofLine: "Frontend for a decentralized exchange experience.",
    role: "Developer",
    stack: ["Web3", "Frontend", "Trading", "Web app"],
    links: { },
    category: "experiment",
  },
  {
    slug: "technical-blog",
    title: "Technical Blog",
    tagline: "Writing on engineering and AI",
    proofLine: "Technical write-ups and project deep dives.",
    role: "Writer",
    stack: ["Writing", "Web", "Documentation", "SEO"],
    links: { demo: "https://nextjs-technical-blog.vercel.app" },
    category: "experiment",
  },
  {
    slug: "portfolio",
    title: "Online Portfolio",
    tagline: "Personal website and project archive",
    proofLine: "Designed and built this portfolio end-to-end.",
    role: "Designer + developer",
    stack: ["Next.js", "TypeScript", "Design", "Content"],
    links: { demo: "https://canyonbryson.com" },
    category: "featured",
  },
  {
    slug: "blujay",
    title: "BluJay",
    tagline: "Social media experiment (Failed)",
    proofLine: "Early-stage social app exploring community mechanics.",
    role: "Founder + developer",
    stack: ["Social", "Mobile", "Flutter"],
    links: {},
    category: "experiment",
  },
  {
    slug: "chesspuzzler",
    title: "ChessPuzzler",
    tagline: "One-day puzzle build",
    proofLine: "Rapid build focused on chess puzzle generation.",
    role: "Solo dev",
    stack: ["Flutter", "Hackathon", "Rapid build", "Game"],
    links: {},
    category: "experiment",
  },
  {
    slug: "fantastic-sudoku",
    title: "Fantastic Sudoku",
    tagline: "First mobile puzzle app",
    proofLine: "Early mobile app focused on sudoku gameplay.",
    role: "Solo dev",
    stack: ["Mobile app", "Flutter", "Game"],
    links: {},
    category: "experiment",
  },
];

export const featuredProjects = projects.filter(
  (p) => p.category === "featured"
);
export const archiveProjects = projects.filter((p) => p.category !== "featured");
